"""Complete English and Simplified Chinese application message catalogs."""


ENGLISH_MESSAGES = {
    "openFile": "Open File…",
    "openFileDetail": "Open one image or annotation document",
    "quit": "Quit",
    "quitApp": "Quit application",
    "openDir": "Open Image Directory",
    "openDirDetail": "Open a directory of images as the annotation workspace",
    "directoryLoading.stop": "Stop indexing",
    "directoryLoading.resume": "Resume indexing",
    "directoryLoading.discovering": "Discovering images…",
    "directoryLoading.annotation": "Indexing annotation directory…",
    "directoryLoading.indexing": "Directory ready · indexing {count} files…",
    "directoryLoading.stopped": "Indexing stopped",
    "directoryLoading.complete": "Indexed {count} files",
    "directoryLoading.failed": "Directory loading failed: {error}",
    "copyPrevBounding": "Copy Previous Annotations",
    "changeSavedAnnotationDir": "Choose where annotations for this workspace are read and saved",
    "openAnnotation": "Replace Current Annotations…",
    "openAnnotationDetail": "Replace the current image's annotations with another annotation document",
    "changeSaveDir": "Choose Annotation Directory…",
    "annotationDirectory.menu": "Annotation Directory",
    "annotationDirectory.currentImage": "Current: Same as Image Directory",
    "annotationDirectory.currentCustom": "Current: {name}",
    "annotationDirectory.statusImage": "Annotation Directory: Same as Image Directory",
    "annotationDirectory.statusCustom": "Annotation Directory: {name}",
    "annotationDirectory.imageTooltip": "Annotations are read from and saved beside each image",
    "annotationDirectory.useImage": "Use Image Directory",
    "nextImg": "Next Image",
    "nextImgDetail": "Open the next image",
    "prevImg": "Previous Image",
    "prevImgDetail": "Open the previous image",
    "verifyImg": "Mark as Verified",
    "verifyImgDetail": "Mark the current image as verified",
    "save": "Save",
    "saveDetail": "Save annotations",
    "changeSaveFormat": "Change save format",
    "saveAs": "Save As",
    "saveAsDetail": "Save annotations to another file",
    "closeCur": "Close",
    "closeCurDetail": "Close the current file",
    "deleteImg": "Delete Current Image",
    "deleteImgDetail": "Delete the current image",
    "resetAll": "Reset All Settings",
    "resetAllDetail": "Reset all settings",
    "boxLineColor": "Box Line Color",
    "boxLineColorDetail": "Choose the default box line color",
    "crtBox": "Draw Box",
    "crtBoxDetail": "Draw a new annotation box",
    "delBox": "Delete Selected Boxes",
    "delBoxDetail": "Delete the selected boxes",
    "dupBox": "Duplicate Selected Boxes",
    "dupBoxDetail": "Duplicate the selected boxes",
    "editBox": "&Edit Boxes",
    "editBoxDetail": "Move and edit boxes",
    "hideAllBox": "&Hide All Boxes",
    "showAllBox": "&Show All Boxes",
    "tutorialDefault": "Tutorial",
    "tutorialChrome": "Tutorial (Chrome)",
    "tutorialDetail": "Show the tutorial",
    "info": "About LabelImg Enhanced",
    "shortcut": "Keyboard Shortcuts",
    "zoomin": "Zoom In",
    "zoominDetail": "Increase the zoom level",
    "zoomout": "Zoom Out",
    "zoomoutDetail": "Decrease the zoom level",
    "originalsize": "Original Size",
    "originalsizeDetail": "Zoom to the original size",
    "fitWin": "Fit Window",
    "fitWinDetail": "Fit the image to the window",
    "fitWidth": "Fit Width",
    "fitWidthDetail": "Fit the image to the window width",
    "editLabel": "Edit Label",
    "editLabelDetail": "Edit the selected box label",
    "shapeLineColor": "Box Line Color",
    "shapeLineColorDetail": "Change the selected boxes' line color",
    "shapeFillColor": "Box Fill Color",
    "shapeFillColorDetail": "Change the selected boxes' fill color",
    "showHide": "Annotation Panel",
    "useDefaultLabel": "Use Default Label",
    "useDifficult": "Difficult Sample",
    "boxLabelText": "Annotations",
    "labels": "Labels",
    "autoSaveMode": "Autosave",
    "singleClsMode": "Single Class Mode",
    "displayLabel": "Show Box Labels",
    "fileList": "File List",
    "files": "Files",
    "showAllBoxDetail": "Show all boxes",
    "hideAllBoxDetail": "Hide all boxes",
    "menu_file": "&File",
    "menu_edit": "&Edit",
    "menu_view": "&View",
    "menu_image": "&Image",
    "menu_settings": "&Settings",
    "menu_help": "&Help",
    "imageTools.title": "Image Tools",
    "imageTools.scope": "Scope",
    "imageTools.scope.current": "Current image",
    "imageTools.scope.selected": "Selected images ({count})",
    "imageTools.tools": "Tools",
    "imageTools.removeFrames": "Remove Red/Yellow Borders",
    "imageTools.targets": "Images",
    "imageTools.target": "Image",
    "imageTools.status": "Status",
    "imageTools.status.queued": "Queued",
    "imageTools.status.processing": "Processing…",
    "imageTools.status.ready": "Ready",
    "imageTools.status.noFrame": "No border detected",
    "imageTools.status.unsupported": "Unsupported",
    "imageTools.status.failed": "Failed",
    "imageTools.status.excluded": "Excluded",
    "imageTools.preview": "Preview",
    "imageTools.preview.original": "Original",
    "imageTools.preview.result": "Result",
    "imageTools.preview.mask": "Repair mask",
    "imageTools.preview.pending": "Preparing preview…",
    "imageTools.preview.summary": "Detected {detected} borders; {selected} selected for removal.",
    "imageTools.colors": "Border Colors",
    "imageTools.color": "Color",
    "imageTools.color.red": "Red",
    "imageTools.color.yellow": "Yellow",
    "imageTools.strength": "Detection",
    "imageTools.strength.conservative": "Conservative",
    "imageTools.strength.standard": "Standard",
    "imageTools.strength.loose": "Loose",
    "imageTools.candidates": "Detected Borders",
    "imageTools.candidate": "Border",
    "imageTools.candidateNumber": "Border {number}",
    "imageTools.badge.includedTooltip": "Border {number} | {color} | Will be removed; click to exclude",
    "imageTools.badge.excludedTooltip": "Border {number} | {color} | Excluded; click to include",
    "imageTools.advanced": "Advanced",
    "imageTools.normalizeGrayscale": "Normalize the whole image to grayscale",
    "imageTools.inpaintRadius": "Inpaint radius",
    "imageTools.halo": "Mask halo",
    "imageTools.undo": "Undo",
    "imageTools.redo": "Redo",
    "imageTools.apply": "Apply",
    "imageTools.commitFailedTitle": "Image Processing Failed",
    "imageTools.commitFailed": "The original images were kept unchanged.\n{error}",
    "imageTools.action.removeFrames": "Remove Red/Yellow Borders…",
    "imageTools.action.removeFramesTip": "Preview and remove red or yellow rectangular borders",
    "crop.action": "Crop…",
    "crop.actionTip": "Crop the current image and update its annotations",
    "geometry.menu": "Rotate / Flip",
    "geometry.rotateClockwise": "Rotate Right",
    "geometry.rotateClockwiseTip": "Rotate the current image and its annotations right by 90°",
    "geometry.rotateCounterclockwise": "Rotate Left",
    "geometry.rotateCounterclockwiseTip": "Rotate the current image and its annotations left by 90°",
    "geometry.rotate180": "Rotate 180°",
    "geometry.rotate180Tip": "Rotate the current image and its annotations by 180°",
    "geometry.flipHorizontal": "Flip Horizontally",
    "geometry.flipHorizontalTip": "Flip the current image and its annotations horizontally",
    "geometry.flipVertical": "Flip Vertically",
    "geometry.flipVerticalTip": "Flip the current image and its annotations vertically",
    "geometry.failedTitle": "Image Transform Failed",
    "geometry.failed": "The image could not be transformed.\n\n{error}",
    "geometry.completed": "Transformed the current image and annotations",
    "geometry.conflict": "Resolve the annotation conflict before transforming the image.",
    "geometry.transform": "Batch Geometry Transform…",
    "geometry.transformTip": "Preview current or selected image geometry changes",
    "geometry.resize": "Resize",
    "geometry.workspace.title": "Transform Image",
    "geometry.workspace.scope": "Target",
    "geometry.workspace.operation": "Operation",
    "geometry.workspace.width": "Width",
    "geometry.workspace.height": "Height",
    "geometry.workspace.percent": "Scale",
    "geometry.enlargeWarning": "Enlarging adds pixels but no source detail. Continue with {percent}%?",
    "adjustment.action": "Adjust Image…",
    "adjustment.actionTip": "Preview and apply pixel corrections",
    "adjustment.title": "Adjust Image",
    "adjustment.brightness": "Brightness",
    "adjustment.contrast": "Contrast",
    "adjustment.gamma": "Gamma (Advanced)",
    "adjustment.autoContrast": "Automatic contrast",
    "adjustment.grayscale": "Convert content to grayscale",
    "adjustment.failedTitle": "Image Adjustment Failed",
    "adjustment.failed": "The image adjustment could not be applied.\n\n{error}",
    "quality.action": "Check Image Quality…",
    "quality.actionTip": "Analyze image quality without modifying files",
    "quality.dialogTitle": "Check Image Quality",
    "quality.minWidth": "Minimum width",
    "quality.minHeight": "Minimum height",
    "quality.maxAspect": "Maximum aspect ratio",
    "quality.blurThreshold": "Blur threshold",
    "quality.darkThreshold": "Dark threshold",
    "quality.overexposedThreshold": "Overexposure threshold",
    "quality.analysisOnly": "Analysis only: this check never changes image files.",
    "quality.panelTitle": "Image Quality",
    "quality.file": "File",
    "quality.findings": "Findings",
    "quality.refresh": "Refresh",
    "quality.clear": "Clear Results",
    "quality.passed": "Passed",
    "quality.summary": "{total} images checked · {issues} with findings",
    "quality.completed": "Checked {count} images",
    "quality.checking": "Checking image quality…",
    "quality.cancelled": "Image quality check cancelled",
    "quality.busy": "An image quality check is already running",
    "quality.failedTitle": "Image Quality Check Failed",
    "quality.failed": "Image quality could not be checked.\n\n{error}",
    "specializedRepair.menu": "Specialized Repair",
    "imageTools.scopeCurrent": "Current image",
    "imageTools.scopeSelected": "Selected images",
    "imageTools.scopeWorkspace": "Workspace",
    "crop.controls": "Crop Controls",
    "crop.ratio": "Ratio",
    "crop.ratio.free": "Free",
    "crop.ratio.original": "Original",
    "crop.ratio.square": "1:1",
    "crop.ratio.fourThree": "4:3",
    "crop.ratio.sixteenNine": "16:9",
    "crop.x": "X",
    "crop.y": "Y",
    "crop.width": "W",
    "crop.height": "H",
    "crop.apply": "Apply Crop",
    "crop.noRegion": "Drag on the image to define a crop region.",
    "crop.confirmTitle": "Apply Crop",
    "crop.confirmImpact": "This crop will clip {clipped} annotation(s) and remove {removed} annotation(s). Continue?",
    "crop.completed": "Cropped the current image",
    "crop.failedTitle": "Crop Failed",
    "crop.failed": "The image and annotations were kept unchanged.\n{error}",
    "crop.leaveTitle": "Crop in Progress",
    "crop.leavePrompt": "Apply the current crop before leaving this image?",
    "crop.leaveApply": "Apply",
    "crop.leaveDiscard": "Discard",
    "imageTools.action.undoCommitted": "Undo Last Image Processing…",
    "imageTools.action.undoCommittedTip": "Restore selected originals from the latest image-processing batch",
    "imageTools.noImage": "Open an image before using image tools.",
    "imageTools.pendingAnnotation": "Finish or cancel the current drawing or drag operation first.",
    "imageTools.completed": "Processed {count} images",
    "imageTools.recovery.title": "Undo Image Processing",
    "imageTools.recovery.instructions": "Select the images to restore. Unselected images remain recoverable in this session.",
    "imageTools.recovery.confirm": "Restore the selected {count} original images? Existing paths will never be overwritten.",
    "imageTools.recovery.none": "There is no recoverable image-processing operation in this session.",
    "menu_openRecent": "Open &Recent",
    "chooseLineColor": "Choose Line Color",
    "chooseFillColor": "Choose Fill Color",
    "drawSquares": "Draw Squares",
    "language.menu": "&Language",
    "language.changed": "Interface language changed to {language}.",
    "common.all": "All",
    "common.cancel": "Cancel",
    "common.available": "Available",
    "fileFilter.title": "Filter Files",
    "fileFilter.placeholder": "Filter by file name or relative path…",
    "fileFilter.annotation": "Annotation State",
    "fileFilter.review": "Review State",
    "fileFilter.persistence": "Persistence State",
    "fileFilter.quality": "Image Quality",
    "fileFilter.clearAll": "Clear All Filters",
    "fileFilter.none": "No Alerts",
    "fileFilter.any": "Has Alerts",
    "fileFilter.qualityIssues": "Has Findings",
    "fileFilter.qualityPassed": "Passed",
    "fileFilter.qualityError": "Errors",
    "fileFilter.qualityWarning": "Warnings",
    "quality.unreadable": "Unreadable",
    "quality.lowResolution": "Low Resolution",
    "quality.aspectAnomaly": "Aspect Anomaly",
    "quality.blur": "Blur",
    "quality.dark": "Too Dark",
    "quality.overexposed": "Overexposed",
    "quality.reasonMetric": "{name}: measured {metric}; threshold {threshold}",
    "quality.reasonUnreadable": "{name}: {detail}",
    "fileSort.name": "File Name",
    "fileSort.modified": "Modified Time",
    "fileSort.annotation": "Annotation State",
    "fileSort.review": "Review State",
    "fileSort.sort": "Sort",
    "fileSort.filter": "Filter",
    "fileSort.ascending": "Ascending",
    "fileSort.descending": "Descending",
    "fileSort.reset": "Reset Sorting",
    "fileSort.tooltip": "Sort: {key} · {direction}",
    "fileFilter.disabled": "Filter: Off",
    "fileFilter.pathContains": "Path contains {text}",
    "fileFilter.annotationValue": "Annotation: {value}",
    "fileFilter.reviewValue": "Review: {value}",
    "fileFilter.alertValue": "Alerts: {value}",
    "fileFilter.qualityValue": "Quality: {value}",
    "fileFilter.tooltip": "Filter: {details}",
    "state.unannotated": "Unannotated",
    "state.annotated": "Annotated",
    "state.unreviewed": "Unreviewed",
    "state.questioned": "Needs Review",
    "state.verified": "Verified",
    "state.dirty": "Unsaved Changes",
    "state.conflict": "External Annotation Conflict",
    "state.ambiguous": "Choose Active Annotation Document",
    "state.degraded": "Read-only Degraded State",
    "renameBatch.title": "Batch Rename",
    "renameBatch.prefix": "Common Prefix",
    "renameBatch.template": "Name Template",
    "renameBatch.suffix": "Common Suffix",
    "renameBatch.sequence": "Sequence",
    "renameBatch.start": "Start Number",
    "renameBatch.width": "Number Width",
    "renameBatch.defaultTemplate": "{original}",
    "renameBatch.help": "The template supports {original} and {sequence}; directories and extensions remain unchanged.",
    "renameBatch.oldPath": "Original Path",
    "renameBatch.newName": "New File Name",
    "renameBatch.validation": "Validation",
    "renameBatch.rename": "Rename",
    "renameBatch.unknownToken": "The template contains an unknown placeholder",
    "renameBatch.resolveErrors": "Resolve the naming conflicts or invalid names in the preview.",
    "renameBatch.unchanged": "The new names are identical to the original names.",
    "renameBatch.ready": "Images and related annotations will be renamed together according to this preview.",
    "renameError.empty": "Name cannot be empty",
    "renameError.invalidChars": "Name contains invalid characters",
    "renameError.trailing": "Name cannot end with a space or period",
    "renameError.reserved": "Name is reserved by Windows",
    "renameError.pathLong": "Full path is too long",
    "renameError.duplicate": "New name duplicates another selected item",
    "renameError.imageExists": "Target image already exists",
    "renameError.annotationExists": "Related annotation target already exists",
    "labelSummary.filtered": "Showing {shown_groups}/{all_groups} label groups · {shown_annotations}/{all_annotations} annotations",
    "labelSummary.all": "{groups} label groups · {annotations} annotations",
    "labelSummary.hiddenSelected": " · {count} more selected annotations are hidden",
    "labelTooltip.group": "{label}｜{annotations} annotations｜{visible} visible｜{selected} selected",
    "labelList.noMatch": "No Matching Label Groups",
    "labelList.clearFilter": "Clear the filter to show all label groups",
    "labelList.empty": "No Annotations in the Current Image",
    "labelList.create": "Press W to create an annotation box",
    "canvas.image": "Image",
    "canvas.ctrlToggle": "Ctrl-click to toggle shape '{label}'",
    "canvas.movePoint": "Click and drag to move the point",
    "canvas.resizeShape": "Click and drag to resize shape '{label}'",
    "canvas.moveShape": "Click and drag to move shape '{label}'",
    "zoom.level": "Zoom Level",
    "labels.filter": "Filter labels…",
    "files.noMatch": "No files match the filters",
    "files.clearFilter": "Clear Filters",
    "action.copyLabels": "Copy Selected Annotations",
    "action.copyLabelsTip": "Copy the selected annotations from the current image",
    "action.pasteLabels": "Paste Annotations",
    "action.pasteLabelsTip": "Paste the copied annotations into the current image",
    "action.questionImage": "Mark as Needs Review",
    "action.questionImageTip": "Mark the current image as needing review",
    "action.tooltipWithShortcut": "{action} ({shortcut})",
    "action.recentOperations": "Recent File Operations…",
    "action.undo": "Undo\tCtrl+Z",
    "action.redo": "Redo\tCtrl+Y / Ctrl+Shift+Z",
    "action.copyHere": "&Copy Here",
    "action.moveHere": "&Move Here",
    "toolbar.tools": "Tools",
    "toolbar.canvasTools": "Canvas Tools",
    "tool.select": "Select / Edit",
    "tool.selectTip": "Select and edit annotations",
    "tool.pan": "Pan",
    "tool.panTip": "Pan the canvas; middle-drag pans temporarily",
    "review.unreviewed": "Unreviewed",
    "review.questioned": "Needs Review",
    "review.verified": "Verified",
    "format.selector": "Annotation format",
    "format.selectorTip": "Choose the annotation format used when saving",
    "image.quickActions": "Image quick actions",
    "navigation.counter": "Image {current} of {total}",
    "zoom.outShort": "Zoom Out",
    "zoom.inShort": "Zoom In",
    "zoom.presets": "Zoom Presets",
    "zoom.help": "Zoom in or out of the image. Also available from the canvas with {keyboard} and {wheel}.",
    "status.started": "{app} started.",
    "status.startedSaveDir": "{app} started. Annotations will be saved to {path}",
    "history.undo": "Undo",
    "history.redo": "Redo",
    "history.cancel": "Cancel {operation}\tCtrl+Z",
    "history.multiple": "{description} {count} boxes",
    "history.create": "Create box",
    "history.drawing": "Drawing",
    "history.resize": "Resize box",
    "history.move": "Move box",
    "history.delete": "Delete boxes",
    "history.deleteSelected": "Delete selected boxes",
    "history.deleteGroup": "Delete label group: {label}",
    "history.changeLabel": "Change label: {old} → {new}",
    "history.renameGroup": "Rename label group: {old} → {new}",
    "history.difficult": "Change difficult flag",
    "history.duplicate": "Duplicate boxes",
    "history.verified": "Toggle verified",
    "history.questioned": "Toggle questioned",
    "history.lineColor": "Change box line color",
    "history.fillColor": "Change box fill color",
    "history.copy": "Copy box",
    "history.paste": "Paste boxes",
    "history.copyPrevious": "Copy previous boxes",
    "labelMenu.edit": "Edit This Annotation Label",
    "labelMenu.hideSelected": "Hide Selected Annotations",
    "labelMenu.hideOne": "Hide This Annotation",
    "labelMenu.showSelected": "Show Selected Annotations",
    "labelMenu.showOne": "Show This Annotation",
    "labelMenu.deleteSelected": "Delete {count} Selected Annotations",
    "labelMenu.deleteOne": "Delete This Annotation",
    "labelMenu.selectGroup": "Select {count} Annotations in This Label Group",
    "labelMenu.renameGroup": "Rename This Label Group",
    "labelMenu.hideGroup": "Hide This Label Group",
    "labelMenu.showGroup": "Show This Label Group",
    "labelMenu.isolateGroup": "Show Only This Label Group",
    "labelMenu.showAllGroups": "Show All Label Groups",
    "labelMenu.deleteGroup": "Delete {count} Annotations in This Label Group",
    "status.deletedAnnotations": "Deleted {count} annotations｜Ctrl+Z to undo",
    "fileCount.selected": "{selected} selected / {total} total",
    "fileCount.total": "{total} files",
    "fileCount.visible": "Showing {visible}/{total}",
    "fileCount.selectedShort": "{selected} selected",
    "fileCount.hidden": " ({hidden} hidden)",
    "fileCount.currentHidden": "Current image is hidden by filters",
    "fileMenu.selectAll": "Select All",
    "fileMenu.open": "Open",
    "fileMenu.rename": "Rename…",
    "fileMenu.batchRename": "Batch Rename…",
    "fileMenu.reveal": "Show in File Explorer",
    "fileMenu.setReview": "Set Review State",
    "fileMenu.markVerified": "Mark as Verified",
    "fileMenu.markQuestioned": "Mark as Needs Review",
    "fileMenu.clearReview": "Clear Review State",
    "fileMenu.select": "Select",
    "fileMenu.invert": "Invert Selection",
    "fileMenu.byAnnotation": "Select by Annotation State",
    "fileMenu.byReview": "Select by Review State",
    "fileMenu.clearSelection": "Clear Selection",
    "fileMenu.copy": "Copy",
    "fileMenu.fileName": "File Name",
    "fileMenu.relativePath": "Relative Path",
    "fileMenu.fullPath": "Full Path",
    "fileMenu.clearAnnotations": "Clear All Annotations for {count} Selected Files…",
    "fileMenu.deleteFiles": "Delete {count} Selected Files…",
    "review.confirm": "Apply “{action}” to {count} selected files?",
    "review.partialFailure": "Some Review States Could Not Be Saved",
    "status.reviewUpdated": "Updated review state for {count} files",
    "fileOps.clearTitle": "Clear All Annotations",
    "fileOps.clearConfirm": "Clear {annotations} annotation files for {files} selected files?\nImages will be kept and annotations will be moved to the system Recycle Bin.\nUnsaved annotations for the current image will also be discarded.",
    "fileOps.clearing": "Clearing annotations…",
    "fileOps.clear": "Clear Annotations",
    "fileOps.deleteTitle": "Delete Selected Files",
    "fileOps.deleteConfirm": "Delete {count} selected files?\nImages and related annotations will be moved to the system Recycle Bin.",
    "fileOps.deleting": "Deleting files…",
    "fileOps.delete": "Delete Files",
    "fileOps.manualRecoveryTitle": "Manual Recycle Bin Recovery Required",
    "fileOps.manualRecovery": "{count} items were moved to the system Recycle Bin, but this platform did not return stable recovery identities. Restore them manually from the system Recycle Bin.",
    "fileOps.partialFailure": "{title} Partially Failed",
    "fileOps.complete": "{title} complete: {count} files",
    "fileOps.canceled": " (remaining operations canceled)",
    "rename.title": "Rename",
    "rename.prompt": "New file name (extension {extension} remains unchanged)",
    "rename.unavailable": "Rename Is Currently Unavailable",
    "rename.resolveConflicts": "Resolve annotation resource conflicts before renaming files.",
    "rename.failed": "Rename Failed",
    "rename.unable": "Unable to Rename",
    "status.renamed": "Renamed {count} files",
    "error.fileManager": "Could Not Open File Manager",
    "error.saveLabelData": "Error Saving Annotation Data",
    "info.title": "About LabelImg Enhanced",
    "info.message": "Name: {name}\nApp Version: {version}\nPython: {python}",
    "recovery.title": "Recent File Operations",
    "recovery.time": "Time",
    "recovery.operation": "Operation",
    "recovery.targets": "Targets",
    "recovery.status": "Status",
    "recovery.recover": "Recover",
    "recovery.confirmTitle": "Recover File Operation",
    "recovery.confirm": "Recover the complete “{operation}” operation affecting {count} targets? Existing paths will never be overwritten.",
    "recovery.blocked": "Recovery Blocked",
    "recovery.failed": "Recovery Failed",
    "recovery.completed": "Recovered file operation",
    "recovery.operation.delete": "Delete",
    "recovery.operation.clear": "Clear Annotations",
    "recovery.operation.rename": "Rename",
    "recovery.operation.review": "Review State",
    "recovery.operation.imageProcessing": "Image Processing",
    "recovery.status.recoverable": "Recoverable",
    "recovery.status.conflict": "Conflict",
    "recovery.status.manual trash": "Manual Recovery Required",
    "recovery.status.restored": "Restored",
    "recovery.status.unavailable": "Unavailable",
    "conflict.autosavePaused": "Autosave paused: annotation files changed outside LabelImg",
    "conflict.title": "Annotation File Conflict",
    "conflict.changed": "The annotation resource changed outside LabelImg.",
    "conflict.options": "Load the external version, overwrite it with the current in-memory version, or cancel.",
    "conflict.loadExternal": "Load External",
    "conflict.overwriteExternal": "Overwrite External",
    "conflict.resolveTitle": "Resolve Annotation Conflicts",
    "conflict.resolvePrompt": "Choose a resolution for every external annotation conflict.",
    "conflict.resource": "Resource",
    "conflict.resolution": "Resolution",
    "common.choose": "Choose…",
    "conflict.applyAll": "Apply to All…",
    "conflict.loadAll": "Load External for All",
    "conflict.overwriteAll": "Overwrite External for All",
    "conflict.loadSharedTitle": "Load Shared External Resource",
    "conflict.loadShared": "Loading this resource affects {images} images and discards changes in {dirty} dirty images. Continue?",
    "conflict.resolveFailed": "Conflict Resolution Failed",
    "conflict.imageTitle": "Image File Conflict",
    "conflict.imageChanged": "The image itself changed externally. Reload the external image before saving annotations.",
    "conflict.overwriteSharedTitle": "Overwrite Shared External Resource",
    "conflict.overwriteShared": "Overwriting this resource affects {images} images and writes changes from {dirty} dirty images. Continue?",
    "conflict.saveFailed": "Unable to Save Annotation Changes",
    "conflict.discardFailed": "Unable to Discard Annotation Changes",
    "conflict.storedChanged": "The stored annotation resource changed externally.",
    "fileStatus.ambiguous": "Choose an active annotation format",
    "fileStatus.degraded": "Read-only degraded annotation state",
    "dialog.saveDirectory": "{app} - Save Annotations to a Directory",
    "status.saveDirectoryChanged": "Annotation directory changed to {path}",
    "status.annotationDirectoryUsesImage": "Annotations now use each image's directory",
    "status.selectImage": "Select an image first",
    "dialog.annotationFilter": "Annotation Files ({patterns})",
    "dialog.chooseAnnotation": "{app} - Choose an Annotation File",
    "dialog.openDirectory": "{app} - Open Directory",
    "dialog.imageAnnotationFilter": "Image and Annotation Files ({patterns})",
    "dialog.chooseImageOrAnnotation": "{app} - Choose an Image or Annotation File",
    "dialog.chooseFile": "{app} - Choose File",
    "dialog.fileFilter": "File (*{extension})",
    "open.annotationTitle": "Error Opening Annotation Document",
    "open.imageMissing": "Could not locate the associated image.",
    "open.fileTitle": "Error Opening File",
    "open.invalidImage": "Make sure {path} is a valid image file.",
    "status.errorReading": "Error reading {detail}",
    "status.loaded": "Loaded {name}",
    "open.chooseDocument": "Choose Annotation Document",
    "open.chooseDocumentPrompt": "Multiple annotation formats exist for this image. Choose the active document for this workspace session:",
    "status.finishEdit": "Finish or cancel the current annotation edit first",
    "save.rescueTitle": "Rescue Save As Requires a New Path",
    "save.rescuePrompt": "Choose a path that does not already exist.",
    "status.removedEmpty": "Removed empty annotation file {path}",
    "status.saved": "Saved to {path}",
    "unsaved.title": "Unsaved Annotation Changes",
    "unsaved.prompt": "Choose Save or Discard for every changed image.",
    "unsaved.image": "Image",
    "unsaved.action": "Action",
    "unsaved.save": "Save",
    "unsaved.discard": "Discard",
    "unsaved.attention": "Attention",
    "unsaved.legacyPrompt": "You have unsaved annotation changes. Save them before continuing?\nChoose No to discard the in-memory document.",
    "error.changeAnnotationDir": "Unable to Change Annotation Directory",
    "status.duplicated": "Created {count} annotation copies",
    "status.noSelectedLabels": "Select at least one annotation to copy",
    "status.copiedLabels": "Copied {count} annotations",
    "status.noCopiedLabels": "No copied annotations to paste",
    "status.pastedLabels": "Pasted {count} annotations",
    "color.chooseLine": "Choose Line Color",
    "color.chooseFill": "Choose Fill Color",
    "history.reloadedAfterFailure": "History projection failed; reloaded the verified stored annotation document",
    "history.failureDetail": "Annotation history failed for {image}; editing is disabled. Projection: {projection}; rollback: {rollback}; stored reload: {reload}",
    "history.unavailable": "unavailable",
    "history.undoFailed": "Undo Failed",
    "history.redoFailed": "Redo Failed",
    "standard.ok": "OK",
    "standard.cancel": "Cancel",
    "standard.close": "Close",
    "standard.save": "Save",
    "standard.discard": "Discard",
    "standard.open": "Open",
    "standard.apply": "Apply",
    "standard.reset": "Reset",
    "standard.restoreDefaults": "Restore Defaults",
    "standard.yes": "&Yes",
    "standard.no": "&No",
}


CHINESE_MESSAGES = {
    "openFile": "打开文件…",
    "openFileDetail": "打开单个图像或标注文档",
    "quit": "退出",
    "quitApp": "退出应用程序",
    "openDir": "打开图像目录",
    "openDirDetail": "将包含图像的目录作为标注工作区打开",
    "copyPrevBounding": "复制上一张图像的标注",
    "changeSavedAnnotationDir": "选择当前工作区读取和保存标注的目录",
    "openAnnotation": "替换当前标注…",
    "openAnnotationDetail": "使用另一个标注文档替换当前图像的标注",
    "changeSaveDir": "选择标注目录…",
    "annotationDirectory.menu": "标注目录",
    "annotationDirectory.currentImage": "当前：与图像同目录",
    "annotationDirectory.currentCustom": "当前：{name}",
    "annotationDirectory.statusImage": "标注目录：与图像同目录",
    "annotationDirectory.statusCustom": "标注目录：{name}",
    "annotationDirectory.imageTooltip": "标注从图像所在目录读取并保存到该目录",
    "annotationDirectory.useImage": "使用图像所在目录",
    "nextImg": "下一张图像",
    "nextImgDetail": "打开下一张图像",
    "prevImg": "上一张图像",
    "prevImgDetail": "打开上一张图像",
    "verifyImg": "标记为已验证",
    "verifyImgDetail": "将当前图像标记为已验证",
    "save": "保存",
    "saveDetail": "保存标注",
    "changeSaveFormat": "更改保存格式",
    "saveAs": "另存为",
    "saveAsDetail": "将标注保存到其他文件",
    "closeCur": "关闭",
    "closeCurDetail": "关闭当前文件",
    "deleteImg": "删除当前图像",
    "deleteImgDetail": "删除当前图像",
    "resetAll": "重置全部设置",
    "resetAllDetail": "重置全部设置",
    "boxLineColor": "标注框线条颜色",
    "boxLineColorDetail": "选择标注框的默认线条颜色",
    "crtBox": "绘制标注框",
    "crtBoxDetail": "绘制新的标注框",
    "delBox": "删除所选标注框",
    "delBoxDetail": "删除所选标注框",
    "dupBox": "创建标注框副本",
    "dupBoxDetail": "创建所选标注框的副本",
    "editBox": "编辑标注框(&E)",
    "editBoxDetail": "移动和编辑标注框",
    "hideAllBox": "隐藏全部标注框(&H)",
    "showAllBox": "显示全部标注框(&S)",
    "tutorialDefault": "教程",
    "tutorialChrome": "教程（Chrome）",
    "tutorialDetail": "显示教程",
    "info": "关于 LabelImg Enhanced",
    "shortcut": "键盘快捷键",
    "zoomin": "放大",
    "zoominDetail": "提高缩放级别",
    "zoomout": "缩小",
    "zoomoutDetail": "降低缩放级别",
    "originalsize": "原始大小",
    "originalsizeDetail": "缩放到原始大小",
    "fitWin": "适应窗口",
    "fitWinDetail": "使图像适应窗口",
    "fitWidth": "适应宽度",
    "fitWidthDetail": "使图像适应窗口宽度",
    "editLabel": "编辑标签",
    "editLabelDetail": "编辑所选标注框的标签",
    "shapeLineColor": "标注框线条颜色",
    "shapeLineColorDetail": "更改所选标注框的线条颜色",
    "shapeFillColor": "标注框填充颜色",
    "shapeFillColorDetail": "更改所选标注框的填充颜色",
    "showHide": "标注面板",
    "useDefaultLabel": "使用默认标签",
    "useDifficult": "困难样本",
    "boxLabelText": "标注",
    "labels": "标签",
    "autoSaveMode": "自动保存",
    "singleClsMode": "单类别模式",
    "displayLabel": "在标注框上显示标签",
    "fileList": "文件列表",
    "files": "文件",
    "showAllBoxDetail": "显示全部标注框",
    "hideAllBoxDetail": "隐藏全部标注框",
    "menu_file": "文件(&F)",
    "menu_edit": "编辑(&E)",
    "menu_view": "视图(&V)",
    "menu_image": "图像(&I)",
    "menu_settings": "设置(&S)",
    "menu_help": "帮助(&H)",
    "imageTools.title": "图像工具",
    "imageTools.scope": "处理范围",
    "imageTools.scope.current": "当前图像",
    "imageTools.scope.selected": "已选图像（{count} 张）",
    "imageTools.tools": "工具",
    "imageTools.removeFrames": "去除红色/黄色边框",
    "imageTools.targets": "图像",
    "imageTools.target": "图像",
    "imageTools.status": "状态",
    "imageTools.status.queued": "等待中",
    "imageTools.status.processing": "处理中…",
    "imageTools.status.ready": "可应用",
    "imageTools.status.noFrame": "未检测到边框",
    "imageTools.status.unsupported": "不支持",
    "directoryLoading.stop": "停止索引",
    "directoryLoading.resume": "继续索引",
    "directoryLoading.discovering": "正在发现图像…",
    "directoryLoading.annotation": "正在索引标注目录…",
    "directoryLoading.indexing": "目录已可用 · 正在索引 {count} 个文件…",
    "directoryLoading.stopped": "索引已停止",
    "directoryLoading.complete": "已索引 {count} 个文件",
    "directoryLoading.failed": "目录加载失败：{error}",
    "imageTools.status.failed": "失败",
    "imageTools.status.excluded": "已排除",
    "imageTools.preview": "预览",
    "imageTools.preview.original": "原图",
    "imageTools.preview.result": "结果",
    "imageTools.preview.mask": "修复蒙版",
    "imageTools.preview.pending": "正在生成预览…",
    "imageTools.preview.summary": "检测到 {detected} 个边框；已选择移除 {selected} 个。",
    "imageTools.colors": "边框颜色",
    "imageTools.color": "颜色",
    "imageTools.color.red": "红色",
    "imageTools.color.yellow": "黄色",
    "imageTools.strength": "检测强度",
    "imageTools.strength.conservative": "保守",
    "imageTools.strength.standard": "标准",
    "imageTools.strength.loose": "宽松",
    "imageTools.candidates": "检测到的边框",
    "imageTools.candidate": "边框",
    "imageTools.candidateNumber": "边框 {number}",
    "imageTools.badge.includedTooltip": "边框 {number}｜{color}｜将去除；单击排除",
    "imageTools.badge.excludedTooltip": "边框 {number}｜{color}｜已排除；单击纳入",
    "imageTools.advanced": "高级选项",
    "imageTools.normalizeGrayscale": "将整张图像统一为灰度",
    "imageTools.inpaintRadius": "修复半径",
    "imageTools.halo": "蒙版外扩",
    "imageTools.undo": "撤销",
    "imageTools.redo": "重做",
    "imageTools.apply": "应用",
    "imageTools.commitFailedTitle": "图像处理失败",
    "imageTools.commitFailed": "原图保持不变。\n{error}",
    "imageTools.action.removeFrames": "去除红色/黄色边框…",
    "imageTools.action.removeFramesTip": "预览并去除红色或黄色矩形边框",
    "crop.action": "裁剪…",
    "crop.actionTip": "裁剪当前图像并同步更新其标注",
    "geometry.menu": "旋转/翻转",
    "geometry.rotateClockwise": "向右旋转",
    "geometry.rotateClockwiseTip": "将当前图像及其标注向右旋转 90°",
    "geometry.rotateCounterclockwise": "向左旋转",
    "geometry.rotateCounterclockwiseTip": "将当前图像及其标注向左旋转 90°",
    "geometry.rotate180": "旋转 180°",
    "geometry.rotate180Tip": "将当前图像及其标注旋转 180°",
    "geometry.flipHorizontal": "水平翻转",
    "geometry.flipHorizontalTip": "水平翻转当前图像及其标注",
    "geometry.flipVertical": "垂直翻转",
    "geometry.flipVerticalTip": "垂直翻转当前图像及其标注",
    "geometry.failedTitle": "图像变换失败",
    "geometry.failed": "无法完成图像变换。\n\n{error}",
    "geometry.completed": "已变换当前图像及其标注",
    "geometry.conflict": "请先解决标注冲突，再变换图像。",
    "geometry.transform": "批量几何变换…",
    "geometry.transformTip": "预览当前图像或选中图像的几何变换",
    "geometry.resize": "调整尺寸",
    "geometry.workspace.title": "变换图像",
    "geometry.workspace.scope": "目标",
    "geometry.workspace.operation": "操作",
    "geometry.workspace.width": "宽度",
    "geometry.workspace.height": "高度",
    "geometry.workspace.percent": "缩放比例",
    "geometry.enlargeWarning": "放大会增加像素，但不会增加源图细节。继续放大到 {percent}% 吗？",
    "adjustment.action": "图像调整…",
    "adjustment.actionTip": "预览并应用像素校正",
    "adjustment.title": "图像调整",
    "adjustment.brightness": "亮度",
    "adjustment.contrast": "对比度",
    "adjustment.gamma": "Gamma（高级）",
    "adjustment.autoContrast": "自动对比度",
    "adjustment.grayscale": "将图像内容转换为灰度",
    "adjustment.failedTitle": "图像调整失败",
    "adjustment.failed": "无法应用图像调整。\n\n{error}",
    "quality.action": "检查图像质量…",
    "quality.actionTip": "分析图像质量，不修改图像文件",
    "quality.dialogTitle": "检查图像质量",
    "quality.minWidth": "最小宽度",
    "quality.minHeight": "最小高度",
    "quality.maxAspect": "最大宽高比",
    "quality.blurThreshold": "模糊阈值",
    "quality.darkThreshold": "过暗阈值",
    "quality.overexposedThreshold": "过曝阈值",
    "quality.analysisOnly": "仅分析：此检查不会修改任何图像文件。",
    "quality.panelTitle": "图像质量",
    "quality.file": "文件",
    "quality.findings": "问题",
    "quality.refresh": "刷新",
    "quality.clear": "清除结果",
    "quality.passed": "通过",
    "quality.summary": "已检查 {total} 张图像 · {issues} 张存在问题",
    "quality.completed": "已检查 {count} 张图像",
    "quality.checking": "正在检查图像质量…",
    "quality.cancelled": "已取消图像质量检查",
    "quality.busy": "已有图像质量检查正在运行",
    "quality.failedTitle": "图像质量检查失败",
    "quality.failed": "无法检查图像质量。\n\n{error}",
    "specializedRepair.menu": "专项修复",
    "imageTools.scopeCurrent": "当前图像",
    "imageTools.scopeSelected": "选中图像",
    "imageTools.scopeWorkspace": "工作区",
    "crop.controls": "裁剪控制",
    "crop.ratio": "比例",
    "crop.ratio.free": "自由",
    "crop.ratio.original": "原始比例",
    "crop.ratio.square": "1:1",
    "crop.ratio.fourThree": "4:3",
    "crop.ratio.sixteenNine": "16:9",
    "crop.x": "X",
    "crop.y": "Y",
    "crop.width": "宽",
    "crop.height": "高",
    "crop.apply": "应用裁剪",
    "crop.noRegion": "请在图像上拖动以定义裁剪区域。",
    "crop.confirmTitle": "应用裁剪",
    "crop.confirmImpact": "此次裁剪将裁断 {clipped} 个标注并删除 {removed} 个标注。是否继续？",
    "crop.completed": "已裁剪当前图像",
    "crop.failedTitle": "裁剪失败",
    "crop.failed": "图像和标注保持不变。\n{error}",
    "crop.leaveTitle": "正在裁剪",
    "crop.leavePrompt": "离开当前图像前应用当前裁剪吗？",
    "crop.leaveApply": "应用",
    "crop.leaveDiscard": "放弃",
    "imageTools.action.undoCommitted": "撤销上次图像处理…",
    "imageTools.action.undoCommittedTip": "从最近一次图像处理批次中选择并恢复原图",
    "imageTools.noImage": "请先打开图像，再使用图像工具。",
    "imageTools.pendingAnnotation": "请先完成或取消当前的绘制或拖动操作。",
    "imageTools.completed": "已处理 {count} 张图像",
    "imageTools.recovery.title": "撤销图像处理",
    "imageTools.recovery.instructions": "请选择要恢复的图像。未选择的图像在本次会话中仍可继续恢复。",
    "imageTools.recovery.confirm": "恢复选中的 {count} 张原图吗？现有路径绝不会被覆盖。",
    "imageTools.recovery.none": "本次会话中没有可恢复的图像处理操作。",
    "menu_openRecent": "最近打开(&R)",
    "chooseLineColor": "选择线条颜色",
    "chooseFillColor": "选择填充颜色",
    "drawSquares": "绘制正方形",
    "language.menu": "语言(&L)",
    "language.changed": "界面语言已切换为{language}。",
    "common.all": "全部",
    "common.cancel": "取消",
    "common.available": "可用",
    "fileFilter.title": "筛选文件",
    "fileFilter.placeholder": "筛选文件名或相对路径…",
    "fileFilter.annotation": "标注状态",
    "fileFilter.review": "复核状态",
    "fileFilter.persistence": "持久化状态",
    "fileFilter.quality": "图像质量",
    "fileFilter.clearAll": "清除全部筛选",
    "fileFilter.none": "无告警",
    "fileFilter.any": "有告警",
    "fileFilter.qualityIssues": "有质量问题",
    "fileFilter.qualityPassed": "已通过",
    "fileFilter.qualityError": "错误",
    "fileFilter.qualityWarning": "警告",
    "quality.unreadable": "无法读取",
    "quality.lowResolution": "低分辨率",
    "quality.aspectAnomaly": "宽高比异常",
    "quality.blur": "模糊",
    "quality.dark": "过暗",
    "quality.overexposed": "过曝",
    "quality.reasonMetric": "{name}：测量值 {metric}；阈值 {threshold}",
    "quality.reasonUnreadable": "{name}：{detail}",
    "fileSort.name": "文件名",
    "fileSort.modified": "修改时间",
    "fileSort.annotation": "标注状态",
    "fileSort.review": "复核状态",
    "fileSort.sort": "排序",
    "fileSort.filter": "筛选",
    "fileSort.ascending": "升序",
    "fileSort.descending": "降序",
    "fileSort.reset": "恢复默认排序",
    "fileSort.tooltip": "排序：{key} · {direction}",
    "fileFilter.disabled": "筛选：未启用",
    "fileFilter.pathContains": "路径包含 {text}",
    "fileFilter.annotationValue": "标注：{value}",
    "fileFilter.reviewValue": "复核：{value}",
    "fileFilter.alertValue": "告警：{value}",
    "fileFilter.qualityValue": "质量：{value}",
    "fileFilter.tooltip": "筛选：{details}",
    "state.unannotated": "未标注",
    "state.annotated": "已标注",
    "state.unreviewed": "未复核",
    "state.questioned": "待复核",
    "state.verified": "已验证",
    "state.dirty": "未保存修改",
    "state.conflict": "外部标注冲突",
    "state.ambiguous": "选择活动标注文档",
    "state.degraded": "只读降级状态",
    "renameBatch.title": "批量重命名",
    "renameBatch.prefix": "统一前缀",
    "renameBatch.template": "名称模板",
    "renameBatch.suffix": "统一后缀",
    "renameBatch.sequence": "序号",
    "renameBatch.start": "起始序号",
    "renameBatch.width": "编号位数",
    "renameBatch.defaultTemplate": "{原名}",
    "renameBatch.help": "模板支持 {原名} 和 {序号}；文件目录与扩展名保持不变。",
    "renameBatch.oldPath": "原路径",
    "renameBatch.newName": "新文件名",
    "renameBatch.validation": "校验",
    "renameBatch.rename": "重命名",
    "renameBatch.unknownToken": "模板包含未知占位符",
    "renameBatch.resolveErrors": "请先解决预览中的命名冲突或非法名称。",
    "renameBatch.unchanged": "新名称与原名称完全相同。",
    "renameBatch.ready": "将按当前预览同步重命名图像及关联标注。",
    "renameError.empty": "名称不能为空",
    "renameError.invalidChars": "名称包含非法字符",
    "renameError.trailing": "名称不能以空格或句点结尾",
    "renameError.reserved": "名称是 Windows 保留名称",
    "renameError.pathLong": "完整路径过长",
    "renameError.duplicate": "新名称与另一选中项重复",
    "renameError.imageExists": "目标图像已存在",
    "renameError.annotationExists": "关联标注目标已存在",
    "labelSummary.filtered": "显示 {shown_groups}/{all_groups} 个标签组 · {shown_annotations}/{all_annotations} 个标注",
    "labelSummary.all": "{groups} 个标签组 · {annotations} 个标注",
    "labelSummary.hiddenSelected": " · 另有 {count} 个已选标注未显示",
    "labelTooltip.group": "{label}｜{annotations} 个标注｜可见 {visible}｜已选 {selected}",
    "labelList.noMatch": "没有匹配的标签组",
    "labelList.clearFilter": "清除筛选以显示全部标签组",
    "labelList.empty": "当前图像暂无标注",
    "labelList.create": "按 W 创建标注框",
    "canvas.image": "图像",
    "canvas.ctrlToggle": "按住 Ctrl 单击可切换形状“{label}”的选择状态",
    "canvas.movePoint": "单击并拖动以移动顶点",
    "canvas.resizeShape": "单击并拖动以调整形状“{label}”的大小",
    "canvas.moveShape": "单击并拖动以移动形状“{label}”",
    "zoom.level": "缩放级别",
    "labels.filter": "筛选标签…",
    "files.noMatch": "没有符合筛选条件的文件",
    "files.clearFilter": "清除筛选",
    "action.copyLabels": "复制所选标注",
    "action.copyLabelsTip": "复制当前图像中所选的标注",
    "action.pasteLabels": "粘贴标注",
    "action.pasteLabelsTip": "将已复制的标注粘贴到当前图像",
    "action.questionImage": "标记为待复核",
    "action.questionImageTip": "将当前图像标记为待复核",
    "action.tooltipWithShortcut": "{action}（{shortcut}）",
    "action.recentOperations": "最近文件操作…",
    "action.undo": "撤销\tCtrl+Z",
    "action.redo": "重做\tCtrl+Y / Ctrl+Shift+Z",
    "action.copyHere": "复制到此处(&C)",
    "action.moveHere": "移动到此处(&M)",
    "toolbar.tools": "工具",
    "toolbar.canvasTools": "画布工具",
    "tool.select": "选择/编辑",
    "tool.selectTip": "选择并编辑标注",
    "tool.pan": "平移",
    "tool.panTip": "平移画布；按住鼠标中键拖动可临时平移",
    "review.unreviewed": "未复核",
    "review.questioned": "待复核",
    "review.verified": "已验证",
    "format.selector": "标注格式",
    "format.selectorTip": "选择保存标注时使用的格式",
    "image.quickActions": "图像快捷操作",
    "navigation.counter": "第 {current} 张，共 {total} 张",
    "zoom.outShort": "缩小",
    "zoom.inShort": "放大",
    "zoom.presets": "缩放预设",
    "zoom.help": "缩放图像；也可在画布中使用 {keyboard} 和 {wheel}。",
    "status.started": "{app} 已启动。",
    "status.startedSaveDir": "{app} 已启动。标注将保存到 {path}",
    "history.undo": "撤销",
    "history.redo": "重做",
    "history.cancel": "取消{operation}\tCtrl+Z",
    "history.multiple": "{description}（{count} 个标注框）",
    "history.create": "创建标注框",
    "history.drawing": "绘制",
    "history.resize": "调整标注框大小",
    "history.move": "移动标注框",
    "history.delete": "删除标注框",
    "history.deleteSelected": "删除所选标注框",
    "history.deleteGroup": "删除标签组：{label}",
    "history.changeLabel": "更改标签：{old} → {new}",
    "history.renameGroup": "重命名标签组：{old} → {new}",
    "history.difficult": "更改困难标记",
    "history.duplicate": "复制标注框",
    "history.verified": "切换已验证状态",
    "history.questioned": "切换待复核状态",
    "history.lineColor": "更改标注框线条颜色",
    "history.fillColor": "更改标注框填充颜色",
    "history.copy": "复制标注框",
    "history.paste": "粘贴标注框",
    "history.copyPrevious": "复制上一张图像的标注框",
    "labelMenu.edit": "修改此标注标签",
    "labelMenu.hideSelected": "隐藏所选标注",
    "labelMenu.hideOne": "隐藏此标注",
    "labelMenu.showSelected": "显示所选标注",
    "labelMenu.showOne": "显示此标注",
    "labelMenu.deleteSelected": "删除所选 {count} 个标注",
    "labelMenu.deleteOne": "删除此标注",
    "labelMenu.selectGroup": "选择此标签组的 {count} 个标注",
    "labelMenu.renameGroup": "重命名此标签组",
    "labelMenu.hideGroup": "隐藏此标签组",
    "labelMenu.showGroup": "显示此标签组",
    "labelMenu.isolateGroup": "仅显示此标签组",
    "labelMenu.showAllGroups": "显示所有标签组",
    "labelMenu.deleteGroup": "删除此标签组的 {count} 个标注",
    "status.deletedAnnotations": "已删除 {count} 个标注｜Ctrl+Z 撤销",
    "fileCount.selected": "已选 {selected} / 共 {total}",
    "fileCount.total": "共 {total} 个文件",
    "fileCount.visible": "显示 {visible}/{total}",
    "fileCount.selectedShort": "已选 {selected}",
    "fileCount.hidden": "（隐藏 {hidden}）",
    "fileCount.currentHidden": "当前图像已被筛选隐藏",
    "fileMenu.selectAll": "全选",
    "fileMenu.open": "打开",
    "fileMenu.rename": "重命名…",
    "fileMenu.batchRename": "批量重命名…",
    "fileMenu.reveal": "在文件资源管理器中显示",
    "fileMenu.setReview": "设置复核状态",
    "fileMenu.markVerified": "标记为已验证",
    "fileMenu.markQuestioned": "标记为待复核",
    "fileMenu.clearReview": "清除复核状态",
    "fileMenu.select": "选择",
    "fileMenu.invert": "反选",
    "fileMenu.byAnnotation": "按标注状态选择",
    "fileMenu.byReview": "按复核状态选择",
    "fileMenu.clearSelection": "清除选择",
    "fileMenu.copy": "复制",
    "fileMenu.fileName": "文件名",
    "fileMenu.relativePath": "相对路径",
    "fileMenu.fullPath": "完整路径",
    "fileMenu.clearAnnotations": "清除选中的 {count} 个文件的全部标注…",
    "fileMenu.deleteFiles": "删除选中的 {count} 个文件…",
    "review.confirm": "确定对选中的 {count} 个文件执行“{action}”吗？",
    "review.partialFailure": "部分复核状态未能保存",
    "status.reviewUpdated": "已更新 {count} 个文件的复核状态",
    "fileOps.clearTitle": "清除全部标注",
    "fileOps.clearConfirm": "确定清除选中的 {files} 个文件对应的 {annotations} 个标注文件吗？\n图像文件会保留，标注将移入系统回收站。\n未保存的当前标注也会被丢弃。",
    "fileOps.clearing": "正在清除标注…",
    "fileOps.clear": "清除标注",
    "fileOps.deleteTitle": "删除选中的文件",
    "fileOps.deleteConfirm": "确定删除选中的 {count} 个文件吗？\n图像及关联标注将移入系统回收站。",
    "fileOps.deleting": "正在删除文件…",
    "fileOps.delete": "删除文件",
    "fileOps.manualRecoveryTitle": "需要手动从回收站恢复",
    "fileOps.manualRecovery": "{count} 个项目已移入系统回收站，但当前平台未返回稳定的恢复标识。只能从系统回收站手动恢复。",
    "fileOps.partialFailure": "{title}部分失败",
    "fileOps.complete": "{title}完成：{count} 个文件",
    "fileOps.canceled": "（已取消剩余操作）",
    "rename.title": "重命名",
    "rename.prompt": "新文件名（扩展名 {extension} 保持不变）",
    "rename.unavailable": "重命名暂不可用",
    "rename.resolveConflicts": "请先解决标注资源冲突，再重命名文件。",
    "rename.failed": "重命名失败",
    "rename.unable": "无法重命名",
    "status.renamed": "已重命名 {count} 个文件",
    "error.fileManager": "无法打开文件管理器",
    "error.saveLabelData": "保存标注数据时出错",
    "info.title": "关于 LabelImg Enhanced",
    "info.message": "名称：{name}\n应用版本：{version}\nPython：{python}",
    "recovery.title": "最近文件操作",
    "recovery.time": "时间",
    "recovery.operation": "操作",
    "recovery.targets": "目标数",
    "recovery.status": "状态",
    "recovery.recover": "恢复",
    "recovery.confirmTitle": "恢复文件操作",
    "recovery.confirm": "恢复影响 {count} 个目标的完整“{operation}”操作吗？现有路径绝不会被覆盖。",
    "recovery.blocked": "恢复被阻止",
    "recovery.failed": "恢复失败",
    "recovery.completed": "已恢复文件操作",
    "recovery.operation.delete": "删除",
    "recovery.operation.clear": "清除标注",
    "recovery.operation.rename": "重命名",
    "recovery.operation.review": "复核状态",
    "recovery.operation.imageProcessing": "图像处理",
    "recovery.status.recoverable": "可恢复",
    "recovery.status.conflict": "存在冲突",
    "recovery.status.manual trash": "需要手动恢复",
    "recovery.status.restored": "已恢复",
    "recovery.status.unavailable": "不可恢复",
    "conflict.autosavePaused": "自动保存已暂停：标注文件已在 LabelImg 外部发生更改",
    "conflict.title": "标注文件冲突",
    "conflict.changed": "标注资源已在 LabelImg 外部发生更改。",
    "conflict.options": "请选择加载外部版本、用当前内存版本覆盖外部版本，或取消。",
    "conflict.loadExternal": "加载外部版本",
    "conflict.overwriteExternal": "覆盖外部版本",
    "conflict.resolveTitle": "解决标注冲突",
    "conflict.resolvePrompt": "请为每个外部标注冲突选择解决方式。",
    "conflict.resource": "资源",
    "conflict.resolution": "解决方式",
    "common.choose": "请选择…",
    "conflict.applyAll": "应用到全部…",
    "conflict.loadAll": "全部加载外部版本",
    "conflict.overwriteAll": "全部覆盖外部版本",
    "conflict.loadSharedTitle": "加载共享外部资源",
    "conflict.loadShared": "加载此资源将影响 {images} 张图像，并丢弃 {dirty} 张未保存图像的更改。是否继续？",
    "conflict.resolveFailed": "解决冲突失败",
    "conflict.imageTitle": "图像文件冲突",
    "conflict.imageChanged": "图像本身已在外部更改。请先重新加载外部图像，再保存标注。",
    "conflict.overwriteSharedTitle": "覆盖共享外部资源",
    "conflict.overwriteShared": "覆盖此资源将影响 {images} 张图像，并写入 {dirty} 张未保存图像的更改。是否继续？",
    "conflict.saveFailed": "无法保存标注更改",
    "conflict.discardFailed": "无法丢弃标注更改",
    "conflict.storedChanged": "存储的标注资源已在外部更改。",
    "fileStatus.ambiguous": "选择活动标注格式",
    "fileStatus.degraded": "只读降级标注状态",
    "dialog.saveDirectory": "{app} - 选择标注保存目录",
    "status.saveDirectoryChanged": "标注目录已更改为 {path}",
    "status.annotationDirectoryUsesImage": "标注已恢复为使用图像所在目录",
    "status.selectImage": "请先选择图像",
    "dialog.annotationFilter": "标注文件（{patterns}）",
    "dialog.chooseAnnotation": "{app} - 选择标注文件",
    "dialog.openDirectory": "{app} - 打开目录",
    "dialog.imageAnnotationFilter": "图像和标注文件（{patterns}）",
    "dialog.chooseImageOrAnnotation": "{app} - 选择图像或标注文件",
    "dialog.chooseFile": "{app} - 选择文件",
    "dialog.fileFilter": "文件（*{extension}）",
    "open.annotationTitle": "打开标注文档时出错",
    "open.imageMissing": "找不到关联图像。",
    "open.fileTitle": "打开文件时出错",
    "open.invalidImage": "请确认 {path} 是有效的图像文件。",
    "status.errorReading": "读取失败：{detail}",
    "status.loaded": "已加载 {name}",
    "open.chooseDocument": "选择标注文档",
    "open.chooseDocumentPrompt": "此图像存在多种标注格式。请选择本次工作区会话使用的活动文档：",
    "status.finishEdit": "请先完成或取消当前标注编辑",
    "save.rescueTitle": "救援另存为需要新路径",
    "save.rescuePrompt": "请选择尚不存在的路径。",
    "status.removedEmpty": "已移除空标注文件 {path}",
    "status.saved": "已保存到 {path}",
    "unsaved.title": "未保存的标注更改",
    "unsaved.prompt": "请为每张已更改图像选择保存或丢弃。",
    "unsaved.image": "图像",
    "unsaved.action": "操作",
    "unsaved.save": "保存",
    "unsaved.discard": "丢弃",
    "unsaved.attention": "注意",
    "unsaved.legacyPrompt": "存在未保存的标注更改。是否在继续前保存？\n选择“否”将丢弃内存中的文档。",
    "error.changeAnnotationDir": "无法更改标注目录",
    "status.duplicated": "已创建 {count} 个标注副本",
    "status.noSelectedLabels": "请至少选择一个要复制的标注",
    "status.copiedLabels": "已复制 {count} 个标注",
    "status.noCopiedLabels": "没有可粘贴的已复制标注",
    "status.pastedLabels": "已粘贴 {count} 个标注",
    "color.chooseLine": "选择线条颜色",
    "color.chooseFill": "选择填充颜色",
    "history.reloadedAfterFailure": "历史投影失败；已重新加载经过验证的存储标注文档",
    "history.failureDetail": "图像 {image} 的标注历史失败，编辑已禁用。投影：{projection}；回滚：{rollback}；重新加载存储文档：{reload}",
    "history.unavailable": "不可用",
    "history.undoFailed": "撤销失败",
    "history.redoFailed": "重做失败",
    "standard.ok": "确定",
    "standard.cancel": "取消",
    "standard.close": "关闭",
    "standard.save": "保存",
    "standard.discard": "丢弃",
    "standard.open": "打开",
    "standard.apply": "应用",
    "standard.reset": "重置",
    "standard.restoreDefaults": "恢复默认值",
    "standard.yes": "是(&Y)",
    "standard.no": "否(&N)",
}


CATALOGS = {
    "en": ENGLISH_MESSAGES,
    "zh_CN": CHINESE_MESSAGES,
}
